name: PR CI

on:
  pull_request:
    branches: [ main ]  # change if your default branch is different

permissions:
  contents: write         # needed so the action can push the auto-format commit
  pull-requests: write

jobs:
  format:
    name: Prettier (auto-fix and commit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required so we can push a commit back

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run Prettier (write)
        run: npm run format

      - name: Commit Prettier changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(prettier): auto-format via CI"
          branch: ${{ github.head_ref }}

  typecheck-and-lint:
    name: Typecheck & Lint
    runs-on: ubuntu-latest
    needs: format         # ensure we lint the formatted code
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Typecheck (tsc --noEmit)
        run: npm run typecheck

      - name: ESLint (warnings allowed)
        run: npm run lint
